name: Build minimal CLI image

on:
  workflow_dispatch:

env:
  GH_TOKEN: "${{ github.token }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Runner info
        run: |
          echo "=== CPU ==="
          nproc
          lscpu | grep -E "^(CPU|Model name|Architecture)"
          echo "=== RAM ==="
          free -h
          echo "=== Disk ==="
          df -h / | tail -1

      - name: Checkout
        uses: actions/checkout@v6

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Checkout rsdk
        uses: actions/checkout@v6
        with:
          repository: RadxaOS-SDK/rsdk
          submodules: recursive
          path: .rsdk

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:latest

      - name: Build CLI image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .rsdk
          push: never
          runCmd: |
            set -euo pipefail
            src/bin/rsdk setup
            src/bin/rsdk shell rsdk build --no-pkgs-json radxa-dragon-q6a bookworm cli

      - name: Prepare artifact
        run: |
          cd .rsdk/out/radxa-dragon-q6a*
          sudo chown -R $USER:$GROUPS .
          xz -vT 0 *.img
          ls -lh

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: radxa-dragon-q6a-cli-bookworm
          path: .rsdk/out/radxa-dragon-q6a*/*.img.xz
          compression-level: 0
